# Generated by Django 4.2.16 on 2025-08-08 09:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fields', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='timeline.eventtype')),
            ],
            options={
                'ordering': ['-timestamp', '-id'],
            },
        ),
    ]
